[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Desabilitar secrets scanning para arquivos específicos
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**,node_modules/**,*.js"
  
# Configuração alternativa: desabilitar completamente o secrets scanning
# Use apenas se necessário - não recomendado para produção
# [build.environment]
#   SECRETS_SCAN_ENABLED = "false"
